URLS=[
"client/api/index.html",
"client/api/user.html",
"client/api/runtime.html",
"client/api/common.html",
"client/api/report.html",
"client/api/dp_object.html"
];
INDEX=[
{
"ref":"datapane.client.api",
"url":0,
"doc":" API docs for Datapane Client interface - Report API docs in  datapane.client.api.report.Report "
},
{
"ref":"datapane.client.api.user",
"url":1,
"doc":""
},
{
"ref":"datapane.client.api.user.login",
"url":1,
"doc":"Login to the specified Datapane Server, storing the token within a config-file called  env for future use",
"func":1
},
{
"ref":"datapane.client.api.user.logout",
"url":1,
"doc":"Logout from Datapane Server, removing local credentials",
"func":1
},
{
"ref":"datapane.client.api.user.ping",
"url":1,
"doc":"Ping the Datapane Server to check login credentials",
"func":1
},
{
"ref":"datapane.client.api.runtime",
"url":2,
"doc":""
},
{
"ref":"datapane.client.api.common",
"url":3,
"doc":""
},
{
"ref":"datapane.client.api.report",
"url":4,
"doc":""
},
{
"ref":"datapane.client.api.report.ReportBlock",
"url":4,
"doc":"Base Block class - not used directly"
},
{
"ref":"datapane.client.api.report.ReportBlock.id",
"url":4,
"doc":""
},
{
"ref":"datapane.client.api.report.Blocks",
"url":4,
"doc":"Block objects at as a container that may hold a list of other Blocks object, such as Tables, Plots, and even recursive Blocks"
},
{
"ref":"datapane.client.api.report.Blocks.blocks",
"url":4,
"doc":""
},
{
"ref":"datapane.client.api.report.Markdown",
"url":4,
"doc":"Markdown objects store Markdown text that can be displayed as formatted text when viewing your report"
},
{
"ref":"datapane.client.api.report.Markdown.text",
"url":4,
"doc":""
},
{
"ref":"datapane.client.api.report.File",
"url":4,
"doc":"File blocks store a file that can be displayed and downloaded"
},
{
"ref":"datapane.client.api.report.File.file",
"url":4,
"doc":""
},
{
"ref":"datapane.client.api.report.File.caption",
"url":4,
"doc":""
},
{
"ref":"datapane.client.api.report.Plot",
"url":4,
"doc":"Plot blocks store a Python-based plot, such as Altair, Boken, Matplotlib, or Plotly, that can be displayed in your report"
},
{
"ref":"datapane.client.api.report.Plot.file",
"url":4,
"doc":""
},
{
"ref":"datapane.client.api.report.Plot.caption",
"url":4,
"doc":""
},
{
"ref":"datapane.client.api.report.Table",
"url":4,
"doc":"Table blocks store a dataframe that can be viewed and filtered in your report, and exported to CSV or Excel. Provides pivot-table functionality by default."
},
{
"ref":"datapane.client.api.report.Table.file",
"url":4,
"doc":""
},
{
"ref":"datapane.client.api.report.Table.caption",
"url":4,
"doc":""
},
{
"ref":"datapane.client.api.report.Report",
"url":4,
"doc":"Reports collate plots, text, and tables into an interactive report that can be analysed by users in their Browser  note Blocks can be passed with using arg parameters or the  blocks kwarg, e.g.  dp.Report(plot, table) or  dp.Report(blocks=[plot, table]) Args:  arg_blocks: Blocks to add to report blocks: Allows providing the report blocks as a single list full_width: Set to  True to increase the report width, for instance when creating a dashboard Returns: A  Report object that can be published, saved, etc."
},
{
"ref":"datapane.client.api.report.Report.full_width",
"url":4,
"doc":"When set, the report is full-width suitable for use in a dashboard"
},
{
"ref":"datapane.client.api.report.Report.publish",
"url":4,
"doc":"Publish the report, including its attached assets, to the logged-in Datapane Server",
"func":1
},
{
"ref":"datapane.client.api.report.Report.save",
"url":4,
"doc":"Save the report to a local HTML file Args: path: location to save the HTML file open: set to  True to open the file in your browser after creating standalone: set to  True to create a fully standalone HTML report (this can result in large files)",
"func":1
},
{
"ref":"datapane.client.api.report.Report.preview",
"url":4,
"doc":"Preview the report inside IPython notebooks in browser",
"func":1
},
{
"ref":"datapane.client.api.report.Report.refresh",
"url":5,
"doc":"Update the local representation of the object",
"func":1
},
{
"ref":"datapane.client.api.report.Report.list",
"url":5,
"doc":"Return a list of the resources",
"func":1
},
{
"ref":"datapane.client.api.dp_object",
"url":5,
"doc":""
},
{
"ref":"datapane.client.api.dp_object.BEObjectRef",
"url":5,
"doc":""
},
{
"ref":"datapane.client.api.dp_object.BEObjectRef.endpoint",
"url":5,
"doc":""
},
{
"ref":"datapane.client.api.dp_object.BEObjectRef.res",
"url":5,
"doc":""
},
{
"ref":"datapane.client.api.dp_object.BEObjectRef.list_fields",
"url":5,
"doc":""
},
{
"ref":"datapane.client.api.dp_object.BEObjectRef.dto",
"url":5,
"doc":""
},
{
"ref":"datapane.client.api.dp_object.BEObjectRef.has_dto",
"url":5,
"doc":""
},
{
"ref":"datapane.client.api.dp_object.BEObjectRef.url",
"url":5,
"doc":""
},
{
"ref":"datapane.client.api.dp_object.BEObjectRef.get",
"url":5,
"doc":"",
"func":1
},
{
"ref":"datapane.client.api.dp_object.BEObjectRef.by_id",
"url":5,
"doc":"",
"func":1
},
{
"ref":"datapane.client.api.dp_object.BEObjectRef.post_with_files",
"url":5,
"doc":"",
"func":1
},
{
"ref":"datapane.client.api.dp_object.BEObjectRef.post",
"url":5,
"doc":"post object to api",
"func":1
},
{
"ref":"datapane.client.api.dp_object.BEObjectRef.refresh",
"url":5,
"doc":"Update the local representation of the object",
"func":1
},
{
"ref":"datapane.client.api.dp_object.BEObjectRef.delete",
"url":5,
"doc":"",
"func":1
},
{
"ref":"datapane.client.api.dp_object.BEObjectRef.update",
"url":5,
"doc":"",
"func":1
},
{
"ref":"datapane.client.api.dp_object.BEObjectRef.list",
"url":5,
"doc":"Return a list of the resources",
"func":1
},
{
"ref":"datapane.client.api.dp_object.ExportableObjectMixin",
"url":5,
"doc":"Used by both Assets and Blobs to abstract over uploading/downloading and exporting"
},
{
"ref":"datapane.client.api.dp_object.ExportableObjectMixin.download_df",
"url":5,
"doc":"",
"func":1
},
{
"ref":"datapane.client.api.dp_object.ExportableObjectMixin.download_file",
"url":5,
"doc":"",
"func":1
},
{
"ref":"datapane.client.api.dp_object.ExportableObjectMixin.download_obj",
"url":5,
"doc":"",
"func":1
},
{
"ref":"datapane.client.api.dp_object.UploadableObjectMixin",
"url":5,
"doc":""
},
{
"ref":"datapane.client.api.dp_object.Blob",
"url":5,
"doc":"Used by both Assets and Blobs to abstract over uploading/downloading and exporting"
},
{
"ref":"datapane.client.api.dp_object.Blob.endpoint",
"url":5,
"doc":""
},
{
"ref":"datapane.client.api.dp_object.Blob.upload_df",
"url":5,
"doc":"",
"func":1
},
{
"ref":"datapane.client.api.dp_object.Blob.upload_file",
"url":5,
"doc":"",
"func":1
},
{
"ref":"datapane.client.api.dp_object.Blob.upload_obj",
"url":5,
"doc":"",
"func":1
},
{
"ref":"datapane.client.api.dp_object.Blob.post",
"url":5,
"doc":"post object to api",
"func":1
},
{
"ref":"datapane.client.api.dp_object.Blob.refresh",
"url":5,
"doc":"Update the local representation of the object",
"func":1
},
{
"ref":"datapane.client.api.dp_object.Blob.list",
"url":5,
"doc":"Return a list of the resources",
"func":1
},
{
"ref":"datapane.client.api.dp_object.Script",
"url":5,
"doc":""
},
{
"ref":"datapane.client.api.dp_object.Script.endpoint",
"url":5,
"doc":""
},
{
"ref":"datapane.client.api.dp_object.Script.upload_pkg",
"url":5,
"doc":"",
"func":1
},
{
"ref":"datapane.client.api.dp_object.Script.download_pkg",
"url":5,
"doc":"",
"func":1
},
{
"ref":"datapane.client.api.dp_object.Script.call",
"url":5,
"doc":"Download, install, and call the script with the provided params",
"func":1
},
{
"ref":"datapane.client.api.dp_object.Script.run",
"url":5,
"doc":"(remote) run the given app (cloning if needed?)",
"func":1
},
{
"ref":"datapane.client.api.dp_object.Script.local_run",
"url":5,
"doc":"(local) run the given script",
"func":1
},
{
"ref":"datapane.client.api.dp_object.Script.post",
"url":5,
"doc":"post object to api",
"func":1
},
{
"ref":"datapane.client.api.dp_object.Script.refresh",
"url":5,
"doc":"Update the local representation of the object",
"func":1
},
{
"ref":"datapane.client.api.dp_object.Script.list",
"url":5,
"doc":"Return a list of the resources",
"func":1
},
{
"ref":"datapane.client.api.dp_object.Run",
"url":5,
"doc":""
},
{
"ref":"datapane.client.api.dp_object.Run.endpoint",
"url":5,
"doc":""
},
{
"ref":"datapane.client.api.dp_object.Run.is_complete",
"url":5,
"doc":"Return true if the run has finished",
"func":1
},
{
"ref":"datapane.client.api.dp_object.Run.post",
"url":5,
"doc":"post object to api",
"func":1
},
{
"ref":"datapane.client.api.dp_object.Run.refresh",
"url":5,
"doc":"Update the local representation of the object",
"func":1
},
{
"ref":"datapane.client.api.dp_object.Run.list",
"url":5,
"doc":"Return a list of the resources",
"func":1
},
{
"ref":"datapane.client.api.dp_object.Variable",
"url":5,
"doc":""
},
{
"ref":"datapane.client.api.dp_object.Variable.endpoint",
"url":5,
"doc":""
},
{
"ref":"datapane.client.api.dp_object.Variable.list_fields",
"url":5,
"doc":""
},
{
"ref":"datapane.client.api.dp_object.Variable.create",
"url":5,
"doc":"",
"func":1
},
{
"ref":"datapane.client.api.dp_object.Variable.post",
"url":5,
"doc":"post object to api",
"func":1
},
{
"ref":"datapane.client.api.dp_object.Variable.refresh",
"url":5,
"doc":"Update the local representation of the object",
"func":1
},
{
"ref":"datapane.client.api.dp_object.Variable.list",
"url":5,
"doc":"Return a list of the resources",
"func":1
},
{
"ref":"datapane.client.api.dp_object.Schedule",
"url":5,
"doc":""
},
{
"ref":"datapane.client.api.dp_object.Schedule.endpoint",
"url":5,
"doc":""
},
{
"ref":"datapane.client.api.dp_object.Schedule.list_fields",
"url":5,
"doc":""
},
{
"ref":"datapane.client.api.dp_object.Schedule.create",
"url":5,
"doc":"",
"func":1
},
{
"ref":"datapane.client.api.dp_object.Schedule.update",
"url":5,
"doc":"",
"func":1
},
{
"ref":"datapane.client.api.dp_object.Schedule.post",
"url":5,
"doc":"post object to api",
"func":1
},
{
"ref":"datapane.client.api.dp_object.Schedule.refresh",
"url":5,
"doc":"Update the local representation of the object",
"func":1
},
{
"ref":"datapane.client.api.dp_object.Schedule.list",
"url":5,
"doc":"Return a list of the resources",
"func":1
}
]